CREATE TABLE [dbo].[LineItem]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Created] DATETIME NULL, 
    [PriceSetId] INT NULL, 
    [VariantInventoryManagement] NCHAR(250) NULL, 
    [TotalDiscountSetId] INT NULL, 
    [TotalDiscount] DECIMAL(18, 2) NULL, 
    [TipPaymentGatewaySpecified] BIT NULL, 
    [TipPaymentMethod] NCHAR(250) NULL, 
    [TipPaymentGateway] NCHAR(250) NULL, 
    [Taxable] BIT NULL, 
    [OriginLocationId] INT NULL, 
    [GiftCard] BIT NULL, 
    [Name] NCHAR(100) NULL, 
    [VariantTitle] NCHAR(100) NULL, 
    [VariantId] BIGINT NULL, 
    [Title] NCHAR(100) NULL, 
    [SKU] NCHAR(100) NULL, 
    [RequiresShipping] BIT NULL, 
    [Quantity] INT NULL, 
    [ProductId] BIGINT NULL, 
    [Price] DECIMAL(18, 2) NULL, 
    [Grams] BIGINT NULL, 
    [FulfillmentStatus] NCHAR(250) NULL, 
    [FulfillmentService] NCHAR(250) NULL, 
    [FulfillableQuantity] INT NULL, 
    [Vendor] NCHAR(100) NULL, 
    [FulfillmentLineItemId] BIGINT NULL
)
